### ISSUE TITLE
Is it possible to fetch tasks/comments, filtered by time constraints?

### ISSUE THREAD

**Issue by giuin** [rkaiser0324/export-asana#2]
I am wondering whether it is in place, or planning to be developed, the possibility to fetch tasks/comments based on a time filter only, e.g. the last updated items within a certain number of days.

This would be useful in case the exported data is quite large and would take too long to download all the data in a single session, or to avoid the download of the full data when you wish to update a previous download.

I am completely new to PHP, hence haven't look to the code myself for a long enough time.

**Comment by rkaiser0324** [comment]
The latest commit adds optional `modified_since` and `completed_since` parameters so you can filter the tasks returned.
